### ISSUE TITLE
How to add to Foundry

### ISSUE THREAD

**Issue by Balekin** [MetaMorphic-Digital/complete-card-management#143]
What's the manifest url for this module? How do you install it into Foundry? When I search for this in Foundry it doesn't show up.

**Comment by esandvik** [comment]
Its in the module.json file at the bottom.  Currently line 76

**Comment by JPMeehan** [comment]
The [Official Release](https://github.com/MetaMorphic-Digital/complete-card-management/releases/tag/v1.0.0) has a link; https://github.com/MetaMorphic-Digital/complete-card-management/releases/download/v1.0.0/module.json

Hopefully this will be resolved soon on the Foundry end!
