### ISSUE TITLE
Deal window is a jumbled mess with longer hand names.

### ISSUE THREAD

**Issue by esandvik** [MetaMorphic-Digital/complete-card-management#144]
When clicking the deal button on a deck if the hand names aren't short enough the window becomes an unusable jumble.  The window is locked so I can't expand it to make more room.
![Default_Window](https://github.com/user-attachments/assets/0db938f3-2781-4890-bf23-c7ac05d99914)
![CCM_Window](https://github.com/user-attachments/assets/1c51068c-55fd-493b-9f72-d3e5d6623fc4)

**Comment by JPMeehan** [comment]
Also an issue in the core deal window but it's definitely something we can fix

**Comment by krbz999** [comment]
We should add the `stacked` css class to this form group. Probably add `white-space: nowrap` to the grid as well.

**Comment by JPMeehan** [comment]
Alternative solution: Just use multi-select instead of multi-checkbox.

![image](https://github.com/user-attachments/assets/565922a1-4999-4e7c-9b48-ed49f250e3a0)
